a = input('Digite algo')
print (f'{a} É um',type(a))
print('Só tem espaços ?',a.isspace())
print('É um número ?',a.isnumeric())
print('É alfabetico ?',a.isalpha())
print('É alfanúmercico ?',a.isalnum())
print('Ele ta tudo em maiusculo ?',a.isupper())
print('Ele ta tudo em minusculo ?',a.islower())
print('Está Capitalizada ?',a.istitle())